### ISSUE TITLE
dude it doesn't work I deployed it in heroku and the app is a blank page

### ISSUE THREAD

**Issue by stewpidtnlvr** [tango-cash/Soundcloud-Proxy#10]

**Comment by jwcnewton** [comment]
Hey @stewpidtnlvr do you have a link to the heroku page?

**Comment by stewpidtnlvr** [comment]
@jwcnewton https://olliesscrapyscraper.herokuapp.com/

**Comment by jwcnewton** [comment]
@stewpidtnlvr Sorry took me a while to get to this, soundcloud have updated the api I have changed the reference and updated the readme.

After deploying it to heroku you will need to set up 2 variables, see https://devcenter.heroku.com/articles/config-vars
CLIENT_ID and USER_ID. The user is is the soundcloud user's stream that you want to display and the client id is your own id to allow connections to the API.

This project was a quick hack and not one I expected anyone to use! I'm happy you have pick it up let me know if you need anything else.

Redeploy, add the vars then head to:
https://olliesscrapyscraper.herokuapp.com/getSoundcloudIframes

**Comment by jwcnewton** [comment]
@stewpidtnlvr This has been resolved in this [commit](https://github.com/tango-cash/Soundcloud-Proxy/commit/ed43a021a0100b2debe4895173e30a27bcb0aef8)
